# Generated by Django 4.2 on 2025-10-21 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المريض')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('date', models.DateField(verbose_name='تاريخ الموعد')),
                ('time', models.TimeField(verbose_name='الوقت')),
                ('message', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctor', verbose_name='الطبيب')),
            ],
        ),
    ]
