# Generated by Django 4.2 on 2025-10-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المريض')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='العمر')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
