# Generated by Django 4.2 on 2025-11-19 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, verbose_name='نوع المصروف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('date', models.DateField(auto_now_add=True, verbose_name='التاريخ')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الخدمة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200, verbose_name='اسم المريض')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('date', models.DateField(auto_now_add=True, verbose_name='التاريخ')),
                ('paid', models.BooleanField(default=True, verbose_name='تم الدفع؟')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.service', verbose_name='الخدمة')),
            ],
        ),
    ]
