# Generated by Django 4.2 on 2025-11-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_expense_service_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('income', models.FloatField()),
                ('expense', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='service',
        ),
        migrations.AddField(
            model_name='invoice',
            name='number',
            field=models.CharField(default='0000', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
