# Generated by Django 4.2 on 2025-11-21 13:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_doctorschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='appointment',
        ),
        migrations.AddField(
            model_name='appointment',
            name='service_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر الكشف'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.appointment'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='main.invoice'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
