# Generated by Django 4.2 on 2025-11-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_payment_appointment_appointment_service_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service_price',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10, verbose_name='سعر الكشف'),
        ),
    ]
