# Generated by Django 4.2 on 2025-11-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_invoice_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='disease',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
